Created secure-key-management.md
sigstore/docs pull request #105
Opened 2023-04-01 07:38 UTC by ro4i7

#### Summary
Close #72  

#### Release Note

#### Documentation

2023-04-01 07:39 UTC, ro4i7 commented
@lkatalin please check this, if it can be merged.

2023-04-01 15:58 UTC, ltagliaferri requested changes
I believe the original issue is asking for a procedural guide with commands of each of these points, and there is some concern that the text is being generated. If this is not generated text, we may be able to use some of this text as a first pass, but the language should have some more detail (for example, in `## Verifying public keys` step 1 does not offer _how_  one would retrieve the public key from the TUF repository)

2023-04-01 15:58 UTC, ltagliaferri commented on content/en/rekor/secure-key-management.md
> +A guide or document that outlines the steps for securely using Rekor public keys. Here are some possible sections for the document:
This sentence is strange and makes me wonder how this text is being generated

2023-04-02 05:16 UTC, haydentherapper commented
There are a number of technical inaccuracies in this documentation. I dont think this addresses the issue either.

2023-04-02 05:23 UTC, ro4i7 commented
> There are a number of technical inaccuracies in this documentation. I dont think this addresses the issue either. This doesn’t have to do with storing keys, it’s about when to use a root of trust from TUF vs using a key provided out of band to verify Rekor. Like the other issue, please take a look at Rekor and follow up with an outline on the issue before writing more documentation.

Ok, I'm working on it.

2023-04-02 15:32 UTC, ltagliaferri commented
Let's close this and continue the discussion on the issue (#72), starting with an outline

2023-04-02 15:32 UTC, closed without merging