choee(docs) adds pkcs11 docs
sigstore/docs pull request #129
Opened 2023-04-16 13:19 UTC by ChrisJBurns

- updates and migrates PKCS11 Tokens docs as part of documentation migration https://github.com/sigstore/cosign/issues/822

This aims to deprecate https://github.com/sigstore/cosign/blob/main/PKCS11.md

Signed-off-by: ChrisJBurns <29541485+ChrisJBurns@users.noreply.github.com>

2023-04-16 13:20 UTC, ChrisJBurns commented
We may want to find a different default image for this one also? instead of using `dlorenc`?

2023-04-18 18:00 UTC, haydentherapper reviewed
Have we confirmed this is up to date and these commands stil work?

2023-04-18 20:58 UTC, ChrisJBurns commented
@haydentherapper  I've not followed the guide, I just worked on the assumption it was up to date. The last commit to the file was made by yourself, so unless you've got a reason to think it may have changed since then? If so I can give it a walk through?

2023-04-18 20:59 UTC, haydentherapper commented
I haven't run through it either, it's just be good to confirm all commands are up to date.

2023-04-25 19:37 UTC, haydentherapper commented
SG then!

2023-04-25 23:10 UTC, znewman01 approved these changes

2023-05-09 20:07 UTC, ltagliaferri requested changes
Just want to upper case ID throughout and remove the reference to a specific username

2023-05-09 20:07 UTC, ltagliaferri commented on content/en/cosign/pkcs11.md
> +$ IMAGE=gcr.io/dlorenc-vmtest2/demo
Can we remove `dlorenc` username throughout?

```suggestion
$ IMAGE=gcr.io/vmtest2/demo
```

2023-05-09 20:07 UTC, ltagliaferri commented on content/en/cosign/pkcs11.md
> +Then, run the command `cosign pkcs11-tool list-tokens` to get the slot id of your token, as follows :
```suggestion
Then, run the command `cosign pkcs11-tool list-tokens` to get the slot ID of your token, as follows :
```

2023-05-09 20:07 UTC, ltagliaferri commented on content/en/cosign/pkcs11.md
> +* **token** and/or **slot-id** : either or both of the PKCS11 token label and the PKCS11 slot id **(mandatory)**
```suggestion
* **token** and/or **slot-id** : either or both of the PKCS11 token label and the PKCS11 slot ID **(mandatory)**
```

2023-05-09 20:07 UTC, ltagliaferri commented on content/en/cosign/pkcs11.md
> +* **object** and/or **id** : either or both of the PKCS11 key label and the PKCS11 key id **(mandatory)**
```suggestion
* **object** and/or **ID** : either or both of the PKCS11 key label and the PKCS11 key ID **(mandatory)**
```

2023-05-09 20:07 UTC, ltagliaferri commented on content/en/cosign/pkcs11.md
> +Pushing signature to: gcr.io/dlorenc-vmtest2/demo:sha256-410a07f17151ffffb513f942a01748dfdb921de915ea6427d61d60b0357c1dcd.sig
```suggestion
Pushing signature to: gcr.io/vmtest2/demo:sha256-410a07f17151ffffb513f942a01748dfdb921de915ea6427d61d60b0357c1dcd.sig
```

2023-05-09 20:07 UTC, ltagliaferri commented on content/en/cosign/pkcs11.md
> +Verification for gcr.io/dlorenc-vmtest2/demo --
```suggestion
Verification for gcr.io/vmtest2/demo --
```

2023-05-09 20:07 UTC, ltagliaferri commented on content/en/cosign/pkcs11.md
> +[{"critical":{"identity":{"docker-reference":"gcr.io/dlorenc-vmtest2/demo"},"image":{"docker-manifest-digest":"sha256:410a07f17151ffffb513f942a01748dfdb921de915ea6427d61d60b0357c1dcd"},"type":"cosign
```suggestion
[{"critical":{"identity":{"docker-reference":"gcr.io/vmtest2/demo"},"image":{"docker-manifest-digest":"sha256:410a07f17151ffffb513f942a01748dfdb921de915ea6427d61d60b0357c1dcd"},"type":"cosign container image signature"},"optional":null}]
```

2023-05-09 20:07 UTC, ltagliaferri commented on content/en/cosign/pkcs11.md
> +Verification for gcr.io/dlorenc-vmtest2/demo --
```suggestion
Verification for gcr.io/vmtest2/demo --
```

2023-05-09 21:21 UTC, ChrisJBurns commented
@ltagliaferri  Sounds good to me! Have committed your suggestions

2023-05-10 02:41 UTC, ltagliaferri approved these changes

2023-05-10 02:41 UTC, merged