Fixed broken link to keyless signing
sigstore/docs pull request #205
Opened 2023-07-27 19:34 UTC by smythp

Resolves #202

2023-07-28 08:06 UTC, cpanato requested changes
thanks for the PR
some things that i think is a bit off

2023-07-28 08:06 UTC, cpanato commented on content/en/cosign/signing_with_containers.md
> +								   --query KeyMetadata.KeyId --output text)
i think you need to remove the tabs and not add it

2023-07-28 08:06 UTC, cpanato commented on content/en/cosign/signing_with_containers.md
> +	  --location=us-central
i think you need to remove the tabs and not add it

2023-07-28 08:06 UTC, cpanato commented on content/en/cosign/signing_with_containers.md
> +			  --query Signature > payload.sig
same here

2023-07-28 08:06 UTC, cpanato commented on content/en/cosign/signing_with_containers.md
> +			   --query SignatureValid
same here

2023-07-28 08:06 UTC, cpanato commented on content/en/cosign/signing_with_containers.md
> +	"digest": "sha256:f5de0db6e714055d48b4bb3a374e9630c4923fa704d9311da6a2740cf625aaba"
same here

2023-07-28 08:06 UTC, cpanato commented on content/en/cosign/signing_with_containers.md
> +	}
same here

2023-07-28 17:34 UTC, ltagliaferri requested changes
Thanks @smythp ! Could you make the changes that @cpanato requested here? Thanks!

2023-07-30 22:05 UTC, ltagliaferri approved these changes

2023-08-04 12:28 UTC, cpanato approved these changes

2023-08-04 12:28 UTC, merged