Docs: Add link to Go installation
sigstore/docs pull request #281
Opened 2023-12-24 14:15 UTC by nikhilkalburgi

#### Summary

Include hyperlink to Go installation in 3 md files (gitsign.md, logging/installation.md, system_config/installation.md)

#### Release Note

NONE

#### Documentation

This PR updates the docs

Resolves sigstore/docs#136

2023-12-29 02:51 UTC, ltagliaferri requested changes
Thanks for adding the link, would be worth doing a copyedit of those lines too, thanks!

2023-12-29 02:51 UTC, ltagliaferri commented on content/en/logging/installation.md
> +If you have [Go](https://go.dev/doc/install) installed, you can use go to retreive the `rekor-cli` binaries
```suggestion
If you have [Go](https://go.dev/doc/install) installed, you can use Go to retrieve the `rekor-cli` binaries
```

2023-12-29 08:27 UTC, nikhilkalburgi commented
Hi @ltagliaferri,
Thank You for Reviewing this PR. 
I have included the suggested change to the squashed commit

**_Also, I want to be part of upcoming events like GSOD, and GSOC. If SIGSTORE participates here, then please consider involving me 😊_**

2024-01-23 00:04 UTC, ltagliaferri approved these changes

2024-01-23 00:04 UTC, merged